//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_type")]
pub enum FileType {
    #[sea_orm(string_value = "Directory")]
    Directory,
    #[sea_orm(string_value = "File")]
    File,
}
